import React from "react";
import {
  FaSlash,
  FaFacebook,
  FaInstagram,
  FaTiktok,
  FaTwitter,
} from "react-icons/fa";
import { FiChevronDown } from "react-icons/fi";

export const Links = [
  {
    id: 0,
    nav: "",
    url: "/",
    linkSymbol: <FiChevronDown />,
  },
  {
    id: 1,
    nav: "Buy",
    url: "/homesForSale",
    linkSymbol: <FiChevronDown />,
  },
  {
    id: 2,
    nav: "Rent",
    url: "/homesForRent",
    linkSymbol: <FiChevronDown />,
  },
  {
    id: 3,
    nav: "Admin",
    url: "/admin",
    linkSymbol: <FiChevronDown />,
  }
];

export const Services = [
  {
    id: 9,
    img: "https://www.zillowstatic.com/s3/homepage/static/Buy_a_home.webp",
    title: " Buy a home",
    text: "Find your place with an immersive photo experience and the most listings, including things you won’t find anywhere else.",
    action: "Search homes",
    to:"/buy"
  },
  {
    id: 11,
    img: "https://www.zillowstatic.com/s3/homepage/static/Rent_a_home.webp",
    title: " Rent a home",
    text: "We’re creating a seamless online experience – from shopping on the largest rental network, to applying, to paying rent.",
    action: "Find rentals",
    to:"/rent"
  },
];

export const MainFooterLinks = [
  {
    id: 12,
    name: "Real Estate",
    Symbol: <FaSlash className="bar fa-0.5x" />,
  },
  {
    id: 13,
    name: "Rentals",
    Symbol: "",
  },
  {
    id: 14,
    name: "Mortgage Rates",
    Symbol: <FaSlash className="bar" />,
  },
  {
    id: 15,
    name: "Browse Homes",
    Symbol: " ",
  },
];
export const SocialMediaLinks = [
  {
    id: 16,
    name: "Facebook",
    socialSymbol: <FaFacebook />,
  },
  {
    id: 17,
    name: "Instagram",
    socialSymbol: <FaInstagram />,
  },
  {
    id: 18,
    name: "TikTok",
    socialSymbol: <FaTiktok />,
  },
  {
    id: 19,
    name: "Twitter",
    socialSymbol: <FaTwitter />,
  },
];

export const HomesForRent = [
  {
    id: 20,
    img: "home1.jpeg",
    price: "$2,050",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 21,
    img: "home1.jpeg",
    price: "$3,550",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 22,
    img: "home1.jpeg",
    price: "$4,550",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 23,
    img: "home1.jpeg",
    price: "$5,550",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 24,
    img: "home1.jpeg",
    price: "3,105",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 25,
    img: "home1.jpeg",
    price: "$4,250",
    beds: 2,
    sqft: 4323,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 26,
    img: "home1.jpeg",
    price: "$2,350",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 27,
    img: "home1.jpeg",
    price: "$5,550",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 28,
    img: "home1.jpeg",
    price: "$4,650",
    beds: 2,
    sqft: 4323,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 29,
    img: "home1.jpeg",
    price: "$3,980",
    beds: 2,
    baths: 1,
    sqft: 4323,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
];

export const HomesForSale = [
  {
    id: 20,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 21,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 22,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 23,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 24,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 25,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 26,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 27,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 28,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
  {
    id: 29,
    img: "home1.jpeg",
    price: "$1550",
    beds: 2,
    baths: 1,
    address: "76 LITTLE BLACKTAIL RD",
    city: "CAREYWOOD",
    state: "ID",
    zip: 83809,
  },
];
